### ISSUE TITLE
Feed improvements

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#247]
There are several issues currently about some items in the generated feed; this issue is for tracking the overall work on these.

- [x] #246 Add itunes:subtitle tag
- [x] #244 feed does not generate itunes titles
- [ ] #168 Allow for customization of titles in feed
